services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
    - ./.env
    ports:
      - '4000:4000'
    depends_on:
      - redis
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=16